import { Container } from "@chakra-ui/layout";
import styles from '../styles/Layout.module.css';
import Script from 'next/script';
import Head from "next/head";
import Footer from "./Footer";
import Nav from "./Nav";

export default function Layout({ children }) {
  return (
    <>
      <Head>
        <title>Karlskrona BJJ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxW='container.xl'>
        <Nav />
        {children}
        <Footer className={styles.footer} />
      </Container>
    </>
  );
}
